on: pull_request
name: Test SSL project
jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Test
          uses: skx/github-action-tester@master
