name: Continuous Integration

on: pull_request
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - macos-latest
    name: Run tests on ${{ matrix.platform }}

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Cache object files
      #   uses: actions/cache@v2
      #   with:
      #     path: ./obj
      #     key: ${{ runner.os }}-build

      - name: Compile
        run: make

      - name: Run tests
        run: ./test/shell/exec.sh

  style:
    runs-on: ubuntu-latest
    name: norminette
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v2
        with:
          flags: 'srcs/* include/* libft/*.c libft/includes/libft.h'
